Implement SDIV opcode
lambdaclass/evm_mlir pull request #114
Opened 2024-05-31 16:30 UTC by JulianVentura

Closes #8 
This PR implements the SDIV opcode.

2024-06-01 22:53 UTC, Oppen commented on src/codegen/operations.rs
> +        .append_operation(arith::divui(num, den, location))
`SDIV` should use `divsi`.

2024-06-01 22:54 UTC, Oppen commented on src/codegen/operations.rs
> +        .append_operation(arith::divui(num, den, location))
Oh, this is for `DIV`. Why is it being changed here?

2024-06-01 22:55 UTC, Oppen commented on src/codegen/operations.rs
> +        constant_value_from_i64(context, &ok_block, (MAX_SHIFT * BITS_PER_BYTE) as i64)?;
These changes seem unrelated to the `SDIV` opcode.

2024-06-01 23:18 UTC, JulianVentura commented on src/codegen/operations.rs
> +        .append_operation(arith::divui(num, den, location))
I just modularized a constant creation function for SDIV as I noticed code repetition, so I refactored some other functions with it. I also added some comments to SDIV for better understanding, so I added them to DIV too because the logic is almost the same.

2024-06-01 23:19 UTC, JulianVentura commented on src/codegen/operations.rs
> +        constant_value_from_i64(context, &ok_block, (MAX_SHIFT * BITS_PER_BYTE) as i64)?;
Unrelated to SDIV. Related to the refactor made while implementing SDIV. See the other comment.

2024-06-03 14:41 UTC, Oppen approved these changes

2024-06-03 14:49 UTC, TomasArrachea commented on tests/operations.rs
> +    let a_biguint = BigUint::from_bytes_be(&a.to_bytes_be().1);
You should use `&a.to_signed_bytes_be()` to represent the negative number as two's complement

2024-06-03 19:06 UTC, Oppen commented on tests/operations.rs
> +        value.to_biguint().unwrap()
```suggestion
    if value.is_positive() {
        value.magnitude().clone()
```

2024-06-03 19:24 UTC, JulianVentura commented on tests/operations.rs
> +        value.to_biguint().unwrap()
Does that `is_positive()` method exist in BigInt? I tried to use something like that but I couldn't find anything, that's why I made that comparison with a constant.
I'll make the change using `magnitude()` instead of the BigUint cast.

2024-06-03 20:57 UTC, Oppen commented on tests/operations.rs
> +        Operation::Push(a), //
There seems to be an unfinished comment here and in other tests?

2024-06-04 13:44 UTC, MegaRedHand requested changes

2024-06-04 13:44 UTC, MegaRedHand commented on src/program.rs
> +    // MOD = 0x06,
This one's duplicated

2024-06-04 13:44 UTC, MegaRedHand commented on tests/operations.rs
> +    if value > BigInt::ZERO {
We can use `is_positive` here

2024-06-04 13:44 UTC, MegaRedHand commented on README.md
> +1. (0x06) MOD
These ones are already implemented

2024-06-04 13:49 UTC, JulianVentura commented on tests/operations.rs
> +    if value > BigInt::ZERO {
We had a discussion about this yesterday. In order to use `is_positive()` we would have to add a new crate to the project, `num_traits`. I can make that addition if you want.

2024-06-04 15:13 UTC, Oppen commented on src/codegen/operations.rs
> +        Operation::Jumpdest { pc } => codegen_jumpdest(op_ctx, region, pc),
Nit: the other operations don't need moving.

2024-06-04 16:02 UTC, JulianVentura commented on README.md
> -1. (0x00) STOP
But STOP operation was implemented, it shouldn't be in the "Not yet implemented" category. Shouldn't I fix that in this PR?

2024-06-04 17:12 UTC, MegaRedHand commented on README.md
> -1. (0x00) STOP
It's OK to fix that. Nice catch!

2024-06-04 17:12 UTC, MegaRedHand commented on tests/operations.rs
> +    if value > BigInt::ZERO {
No need. I forgot we're dealing with `BigInt`s here.

2024-06-04 17:14 UTC, MegaRedHand approved these changes
LGTM. Please merge with main, and be specially careful with `git` duplicating entries in the readme/Opcode enum.

2024-06-04 18:19 UTC, merged