feat: implement OR opcode
lambdaclass/evm_mlir pull request #119
Opened 2024-05-31 18:38 UTC by Danikim01

closes #22 
This PR implements the OR opcode

2024-06-01 23:05 UTC, Oppen commented on tests/operations.rs
> +    run_program_assert_result(program, expected.try_into().unwrap());
```suggestion
    let expected = 0b1110_u8;
    let program = vec![
        Operation::Push(a.clone()),
        Operation::Push(b.clone()),
        Operation::Or,
    ];
    run_program_assert_result(program, expected);
```

2024-06-03 13:34 UTC, Oppen requested changes

2024-06-03 13:34 UTC, Oppen commented on README.md
> +
```suggestion
```

2024-06-03 13:34 UTC, Oppen commented on README.md
> +1. (0x17) OR
Please keep ordered.

2024-06-03 13:34 UTC, Oppen commented on README.md
> -1. (0x10) LT
This shouldn't be removed.

2024-06-03 14:08 UTC, Danikim01 commented on README.md
> -1. (0x10) LT
resolved

2024-06-03 17:18 UTC, Oppen approved these changes
Just need to fix conflicts.

2024-06-03 18:23 UTC, merged