feat : Not opcode and updated readme
lambdaclass/evm_mlir pull request #126
Opened 2024-05-31 22:40 UTC by mahmudsudo

1. #24 Not Opcode implemented with tests
2. readme updated to remove error when running command

2024-06-04 17:09 UTC, MegaRedHand requested changes
Hey there, and thanks again for your contribution! I left you some comments. Also, CI seems not to be running because of conflicts with main.

2024-06-04 17:09 UTC, MegaRedHand commented on src/codegen/operations.rs
> +// from the understanding of the not operator , A xor 1 == Not A
This is correct only for boolean values. Here we're working with 256-bit integers. For them, bitwise NOT is equivalent to `A xor 0xff...ff` (i.e. xor-ing against 256 set bits)

2024-06-05 15:24 UTC, MegaRedHand reviewed
Left you some comments. Once they're addressed I think it'll be ready to merge 😄
Please move the opcode from "not implemented" to "implemented" on the readme.

2024-06-05 15:24 UTC, MegaRedHand commented on src/codegen/operations.rs
> +   mask[31] = 0xff;
The mask should be `[0xff; 32]` (the 256 bits set) for it to work.

2024-06-05 15:24 UTC, MegaRedHand commented on src/codegen/operations.rs
> +    //     .into();
We can remove this

2024-06-05 19:40 UTC, mahmudsudo commented on src/codegen/operations.rs
> +   mask[31] = 0xff;
done

2024-06-05 19:48 UTC, mahmudsudo commented on src/codegen/operations.rs
> +   mask[31] = 0xff;
setting the mask to [0xff;32] makes the test fail whilst 
`
 let mut mask: [u8; 32] = [0; 32];
   mask[31] = 0xff;
`
passes all tests

2024-06-08 01:35 UTC, mahmudsudo commented
#216 reimplements this in line with the changes to the codebase

2024-06-08 01:35 UTC, closed without merging