Implement SHL opcode
lambdaclass/evm_mlir pull request #133
Opened 2024-06-03 18:54 UTC by FrancoGiachetta

Closes #26 
This PR handles the SHL opcode

2024-06-04 18:22 UTC, MegaRedHand requested changes
Looks good, but please add the gas-related changes

2024-06-04 18:22 UTC, MegaRedHand commented on src/codegen/operations.rs
> +    // if shifht is grater than 255
typo
```suggestion
    // if shift is greater than 255
```

2024-06-04 18:27 UTC, FrancoGiachetta commented on src/codegen/operations.rs
> +    // if shifht is grater than 255
Oh, my bad. Checking gas addition.

2024-06-04 21:22 UTC, Oppen approved these changes

2024-06-05 15:10 UTC, MegaRedHand approved these changes
LGTM

2024-06-05 15:11 UTC, merged