feat: load executables dynamically, add memory, and implement RETURN opcode
lambdaclass/evm_mlir pull request #142
Opened 2024-06-03 20:36 UTC by MegaRedHand

Closes #78

2024-06-03 22:11 UTC, azteca1998 approved these changes

2024-06-04 01:38 UTC, juanbono commented on src/utils.rs
> +pub(crate) fn extend_memory<'c>(
I think it will be useful to add some docs here so it can serve as an example of a syscall implementation.

2024-06-04 01:40 UTC, juanbono commented on src/syscall_handler.rs
> +use std::ffi::c_void;
I think a module doc can be useful here to explain the different moving parts

2024-06-04 01:41 UTC, juanbono commented on src/syscall_handler.rs
> +    pub fn result(&self) -> &[u8] {
same here, some docs can be useful to newcomers.

2024-06-04 01:43 UTC, juanbono commented on src/syscall_handler.rs
> +        println!("Extending memory to {new_size}");
here we can use tracing instead of println

2024-06-04 01:46 UTC, juanbono commented on src/context.rs
> +    assert!(res.verify());
he is initializing it to 0

2024-06-04 01:46 UTC, juanbono requested changes
see comments

2024-06-04 02:17 UTC, MegaRedHand commented on src/context.rs
> +    assert!(res.verify());
It's intended. I'm not initializing it because, for any memory access, we'll first check there's enough memory and set this global to the result of `extend_memory` anyways.

2024-06-04 02:18 UTC, MegaRedHand commented on src/syscall_handler.rs
> +        println!("Extending memory to {new_size}");
Good catch! I actually forgot to remove this print 😅

2024-06-04 13:18 UTC, Oppen commented on src/codegen/operations.rs
> +        .append_operation(arith::trunci(offset_u256, uint32.into(), location))
Is the truncation specified? Why did we choose uint32 rather than platform native?

2024-06-04 13:41 UTC, Oppen commented on src/lib.rs
> +        #[cfg(target_os = "windows")]
In fact, the `cfg!` macro as used [here](https://github.com/lambdaclass/evm_mlir/pull/142/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R341-R349) should suffice, considering no OS-specific functions are called.

2024-06-04 13:42 UTC, Oppen commented on src/lib.rs
> +        #[cfg(target_os = "windows")]
(The advantage would be just having an `else` case)

2024-06-04 14:42 UTC, Oppen commented on src/syscall.rs
> +            // TODO: check for OOM
You can do this with [try_reserve](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.try_reserve).

2024-06-04 14:51 UTC, MegaRedHand commented on src/codegen/operations.rs
> +        .append_operation(arith::trunci(offset_u256, uint32.into(), location))
I truncated the number here for simplicity. I'm not sure how we would represent a `usize` in MLIR, and we'd probably run into some weird issues. The max size for the EVM memory is ~4MB according to the block gas limit, so we'll probably never reach it.

2024-06-04 14:53 UTC, MegaRedHand commented on src/codegen/operations.rs
> +        .append_operation(arith::trunci(offset_u256, uint32.into(), location))
I added a comment

2024-06-04 15:00 UTC, MegaRedHand commented on src/syscall.rs
> +            // TODO: check for OOM
Done

2024-06-04 15:33 UTC, Oppen commented on src/syscall.rs
> +//! [`mlir::write_result_syscall`] for an example).
Maybe we can make a helper function for this? It seems like many steps for the implementer to keep in mind. Maybe have `register_syscalls` do the `mlir::declare_syscalls`?

2024-06-04 18:54 UTC, MegaRedHand commented on src/syscall.rs
> +//! [`mlir::write_result_syscall`] for an example).
The thing is both are different steps of the whole workflow, and I think it's better to have them split like this to avoid mixing it in more complex ways. Besides, I think having all of this in a single module should make it simple enough, right?

2024-06-04 18:58 UTC, juanbono approved these changes

2024-06-04 19:19 UTC, merged