feat: Implement CALLDATACOPY opcode
lambdaclass/evm_mlir pull request #202
Opened 2024-06-06 19:25 UTC by Danikim01

closes #37 
This PR implements the CALLDATACOPY opcode

2024-06-10 15:53 UTC, MegaRedHand requested changes

2024-06-10 15:53 UTC, MegaRedHand commented on src/codegen/operations.rs
> +            IntegerAttribute::new(IntegerType::new(context, 1).into(), 1),
This marks the value as volatile? Why?

2024-06-10 15:53 UTC, MegaRedHand commented on src/main.rs
> +// use evm_mlir::program::Operation;
There's commented code here

2024-06-10 15:53 UTC, MegaRedHand commented on src/main.rs
> +
And here

2024-06-10 15:53 UTC, MegaRedHand commented on src/syscall.rs
> +    pub memory: Vec<u8>,
None of these should be public

2024-06-10 15:53 UTC, MegaRedHand commented on tests/operations.rs
> +fn test_calldatacopy() {
Please move tests to `tests/evm.rs`, and use the `Evm` API.

2024-06-11 22:31 UTC, MegaRedHand commented on src/syscall.rs
> +    pub(crate) fn get_memory_pointer_syscall<'c>(
`extend_memory` returns the memory pointer. That's why this one wasn't added.

2024-06-11 22:31 UTC, MegaRedHand commented on src/syscall.rs
> +    pub(crate) fn get_calldata_ptr_syscall<'c>(
This one can be removed, since it's duplicate

2024-06-11 22:31 UTC, MegaRedHand commented on src/codegen/operations.rs
> +    //required size = call_data_offset + size
```suggestion
    // required size = dest_offset + size
```

2024-06-11 22:31 UTC, MegaRedHand commented on src/codegen/operations.rs
> +        .into();
This can be negative, right? Are we handling that case?

2024-06-14 18:05 UTC, Danikim01 commented
> closes #37 This PR implements the CALLDATACOPY opcode

with the new changes closes #242

2024-06-19 13:47 UTC, Danikim01 commented on src/codegen/operations.rs
> +    let memory_ptr = return_memory_pointer(op_ctx, &continue_memory_block, location)?;
resolved

2024-06-19 14:38 UTC, MegaRedHand approved these changes
LGTM

2024-06-19 15:11 UTC, merged