Not opcode
lambdaclass/evm_mlir pull request #216
Opened 2024-06-08 01:27 UTC by mahmudsudo

#24 
This pr implements Not Opcode with appropriate tests

2024-06-19 16:17 UTC, mahmudsudo commented
@MegaRedHand

2024-06-19 16:18 UTC, MegaRedHand reviewed
Sorry! I left some comments but forgot to finish the review 😩

2024-06-19 17:23 UTC, mahmudsudo commented
@MegaRedHand  the comments have been resolved

2024-06-19 17:38 UTC, MegaRedHand requested changes
Left some comments.

2024-06-19 17:38 UTC, MegaRedHand commented on src/codegen/operations.rs
> +            Attribute::parse(context, &format!("{} : i256", BigUint::from(0xff_u8))).unwrap(),
The mask should be 256 bits all set. Here you only set the first 8.

2024-06-19 17:38 UTC, MegaRedHand commented on tests/operations.rs
> +}
Note that this test only expects the last 8 bits of the result to be negated, instead of the whole 256. You can check [the EVM playground](https://www.evm.codes/playground?fork=cancun&unit=Wei&codeType=Mnemonic&code='PUSH1%2090%5CnNOT'_) for the correct result. I suggest the following test:

```rust
let program = vec![Operation::Push0, Operation::Not];
let expected_result = BigUint::from_bytes_be(&[0xff; 32]);
run_program_assert_stack_top(program, expected_result);
```

2024-06-19 20:12 UTC, mahmudsudo commented
@MegaRedHand comments resolved

2024-06-19 20:15 UTC, MegaRedHand approved these changes
Good work! Please fix conflicts so we can merge

2024-06-19 22:30 UTC, mahmudsudo commented
@MegaRedHand conflicts resolved

2024-06-20 17:12 UTC, MegaRedHand requested changes

2024-06-20 17:12 UTC, MegaRedHand commented on tests/operations.rs
> +=======
There's a git merge conflic here.

2024-06-20 17:12 UTC, MegaRedHand commented on tests/operations.rs
>  fn mstore_gas_cost_with_memory_extension() {
And this test is missing the `#[test]` tag

2024-06-20 17:33 UTC, mahmudsudo commented
@MegaRedHand

2024-06-20 19:54 UTC, MegaRedHand approved these changes

2024-06-20 19:59 UTC, MegaRedHand commented on src/program.rs
> +
There's an `Operation::Not` arm missing in this `match`. Due to that, this fails to compile.

2024-06-20 20:40 UTC, mahmudsudo commented
@MegaRedHand

2024-06-20 21:13 UTC, MegaRedHand commented
The CI's failing. Please run `make fmt` to fix it.

2024-06-20 22:18 UTC, mahmudsudo commented
@MegaRedHand

2024-06-20 22:29 UTC, mahmudsudo commented
@MegaRedHand

2024-06-20 23:02 UTC, merged