feat: implement KECCAK256 opcode
lambdaclass/evm_mlir pull request #221
Opened 2024-06-10 15:23 UTC by Danikim01

closes #29 
This PR implements the KEKKACK256 opcode

2024-06-14 21:16 UTC, JulianVentura commented on tests/operations.rs
> +#[test]
Can we add two more tests? One with the [EVM Codes Keccak256 playground example](https://www.evm.codes/playground?unit=Wei&codeType=Mnemonic&code=%27sPutkrequired%20valugin%20memoryj32%200xFFFFFFFFffffz0wMSTOREwwsCallkopcodez4z0wKECCAK256%27~0000000zj1%20w%5Cns%2F%2F%20k%20thgjwPUSHge%20f~~%01fgjkswz~_) and the other one with a stack overflow?

2024-06-18 12:24 UTC, Danikim01 commented on tests/operations.rs
> +#[test]
resolved, i also added a test for underflow.

2024-06-19 14:55 UTC, MegaRedHand requested changes

2024-06-19 14:55 UTC, MegaRedHand commented on src/codegen/operations.rs
> +    let flag = check_stack_has_at_least(context, &start_block, 2)?;
We only need to check the stack has at least two elements here. Popping those two elements will make space for the result.

2024-06-19 21:16 UTC, Danikim01 commented on Cargo.toml
> +hex-literal = "0.4.1"
resolved

2024-06-19 21:17 UTC, Danikim01 commented on src/codegen/operations.rs
> +    let flag = check_stack_has_at_least(context, &start_block, 2)?;
resolved

2024-06-19 21:17 UTC, Danikim01 commented on src/codegen/context.rs
> +    pub(crate) fn keccak256_hasher_syscall(
resolved

2024-06-25 14:06 UTC, MegaRedHand approved these changes
LGTM

2024-06-25 14:29 UTC, merged