feat: CODECOPY opcode
lambdaclass/evm_mlir pull request #237
Opened 2024-06-11 19:46 UTC by ricomateo

Closes #39 
This PR implements code generation for [CODECOPY](https://www.evm.codes/#39?fork=cancun) opcode.

2024-06-19 18:51 UTC, FrancoGiachetta approved these changes
LGTM

2024-06-19 19:38 UTC, MegaRedHand requested changes

2024-06-19 19:38 UTC, MegaRedHand commented on src/main.rs
> -    let opt_level = match args.get(2).map(String::as_str) {
Please revert changes to this file.

2024-06-19 19:38 UTC, MegaRedHand commented on src/program.rs
> +            x if x == Opcode::MSTORE8 as u8 => Opcode::MSTORE8,
These where duplicated

2024-06-19 19:38 UTC, MegaRedHand commented on src/syscall.rs
> +    pub program: Vec<u8>,
This should go inside the `inner_context`

2024-06-19 19:38 UTC, MegaRedHand commented on src/syscall.rs
> +        }
We should use [`Vec::copy_from_slice`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.copy_from_slice) here.

2024-06-19 19:38 UTC, MegaRedHand commented on src/syscall.rs
> +            code_size - code_offset
You can do:

```rust
code_size.checked_sub(code_offset).unwrap_or(0)
```

2024-06-19 19:38 UTC, MegaRedHand commented on src/constants.rs
> +    }
This looks the same as `memory_copy_cost`. Can we reuse that?

2024-06-19 19:38 UTC, MegaRedHand commented on src/utils.rs
> +pub(crate) fn compute_codecopy_gas_cost<'c>(
Isn't this the same as `compute_copy_cost`?

2024-06-19 20:28 UTC, ricomateo commented on src/syscall.rs
> +            code_size - code_offset
I'm trying to do it that way but the linter is throwing this warning 
`help: consider using saturating_sub: code_size.saturating_sub(code_offset)`
 however `saturating_sub` is not useful in this case

2024-06-19 21:11 UTC, MegaRedHand commented on src/syscall.rs
> +            code_size - code_offset
`saturating_sub` is _just_ what we need

2024-06-19 21:50 UTC, JulianVentura commented on src/syscall.rs
> +    pub program: Vec<u8>,
I have a question. Why do we need to store the program here? Can't we access the `Db` to get the bytecode for the callee address?
We access the `TransactTo` address like we do in `ADDRESS` opcode.
Then with that address we access the `Db` to get the bytecode, like we do in `EXTCODESIZE`.

2024-06-24 19:51 UTC, MegaRedHand approved these changes
LGTM

2024-06-24 19:51 UTC, MegaRedHand commented on tests/evm.rs
> +    env.tx.gas_limit = 999_999;
This shouldn't be needed

2024-06-24 19:51 UTC, MegaRedHand commented on tests/evm.rs
> +    env.tx.gas_limit = 999_999;
Neither this one

2024-06-24 19:51 UTC, MegaRedHand commented on src/syscall.rs
> +    pub program: Vec<u8>,
Let's leave this for another PR

2024-06-24 20:18 UTC, MegaRedHand commented on tests/evm.rs
> +    dbg!(env.tx.gas_limit);
```suggestion
```

2024-06-25 12:36 UTC, merged