Opcode GASLIMIT implementation
lambdaclass/evm_mlir pull request #262
Opened 2024-06-13 21:46 UTC by JulianVentura

Closes #51 
This PR implements the GASLIMIT opcode with its tests.

2024-06-19 19:24 UTC, FrancoGiachetta requested changes

2024-06-19 19:24 UTC, FrancoGiachetta commented on src/syscall.rs
> +    #[allow(improper_ctypes)]
This line shouldn't be needed anymore.

2024-06-19 19:24 UTC, FrancoGiachetta commented on src/syscall.rs
> +        value.lo = self.env.tx.gas_limit as u128;
Do we need to represent value as U256? Couldn't it be u64?

2024-06-19 20:05 UTC, FrancoGiachetta requested changes

2024-06-19 20:05 UTC, FrancoGiachetta commented on src/syscall.rs
> +            SyscallContext::get_gaslimit as *const fn(*mut c_void, *mut U256) as *mut (),
I think this `*mut U256` is not need any longer since the syscall is not using it now.

2024-06-19 20:14 UTC, FrancoGiachetta approved these changes

2024-06-19 20:14 UTC, FrancoGiachetta commented
LGTM
@MegaRedHand

2024-06-24 19:56 UTC, MegaRedHand reviewed
Please check the setting of `env.tx.gas_limit`. I think most of them are OK with the default

2024-06-24 19:56 UTC, MegaRedHand commented on tests/evm.rs
> +    env.tx.gas_limit = 999_999;
Why is this needed?

2024-06-24 19:56 UTC, MegaRedHand commented on tests/evm.rs
> +    env.tx.gas_limit = 999_999;
Is this needed?

2024-06-25 23:11 UTC, MegaRedHand approved these changes
LGTM

2024-06-25 23:12 UTC, merged