Use calldata globals instead of syscalls
lambdaclass/evm_mlir pull request #270
Opened 2024-06-14 21:02 UTC by Danikim01

closes #269 
This PR removes the use syscalls in calldataload opcode

2024-06-18 14:48 UTC, JulianVentura commented on src/utils.rs
> +    // let zero = block
Here you forgot some commented code. Please, delete it.

2024-06-18 14:48 UTC, JulianVentura commented on src/utils.rs
> +    //Ok(calldata_size_syscall)
More commented code.

2024-06-18 14:48 UTC, JulianVentura commented on src/utils.rs
> +    //let uint32 = IntegerType::new(context, 32).into();
More commented code

2024-06-24 20:27 UTC, TomasArrachea reviewed
LGTM

2024-06-25 14:17 UTC, MegaRedHand commented on src/utils.rs
> +pub(crate) fn return_calldata_ptr<'c>(
We should rename these `return_*` functions to `get_*` to avoid confusion

2024-06-25 14:17 UTC, MegaRedHand commented on src/utils.rs
> +pub(crate) fn setup_calldata_ptr<'c>(
These `setup_*` functions are used only once when initializing the `OperationCtx`. We should move them there

2024-06-25 14:17 UTC, MegaRedHand commented on src/codegen/context.rs
> -        generate_calldata_setup_code(context, module, setup_block)?;
This was OK here. Just pass `syscall_ctx` as parameter.

2024-06-25 14:17 UTC, MegaRedHand commented on src/codegen/context.rs
> -fn generate_calldata_setup_code<'c>(
This was mostly OK. It just needed to use the correct values.

2024-06-25 14:17 UTC, MegaRedHand requested changes
Left some comments

2024-06-27 14:47 UTC, MegaRedHand approved these changes
LGTM

2024-06-27 14:47 UTC, merged