feat: BALANCE Opcode
lambdaclass/evm_mlir pull request #273
Opened 2024-06-18 13:50 UTC by FrancoGiachetta

Closes #31 
This PR handles the implementation of BALANCE opcode

2024-06-18 18:40 UTC, FrancoGiachetta commented
Don't really know if the attributes of DbAccounts were private on purpose. I made them public so that I could make the tests.

2024-06-18 19:25 UTC, JulianVentura commented on tests/evm.rs
> +use ethereum_types::Address;
Please, import types from `src/primitives.rs`

2024-06-18 19:25 UTC, JulianVentura commented on tests/evm.rs
> +    dbg!("Balance2 {}", balance);
Here there is another debug log

2024-06-18 19:25 UTC, JulianVentura commented on tests/evm.rs
> +    let address = Address::from_low_u64_be(123456);
Can you please modify this test to match the [example of the EVM Codes](https://www.evm.codes/playground?callValue=125985&unit=Wei&codeType=Mnemonic&code=%27%2F%2F%20Read%20current%20contract%20balance%5CnADDRESS%5CnBALANCE%27_)? You can look at [CALLER](https://github.com/lambdaclass/evm_mlir/pull/260) or [ADDRESS](https://github.com/lambdaclass/evm_mlir/pull/254) PRs to see an example.

2024-06-18 19:40 UTC, FrancoGiachetta commented on README.md
> +1. (0x43) NUMBER
This thing is that a realized a forgot to change it on that PR.

2024-06-18 21:27 UTC, JulianVentura commented on README.md
> +1. (0x43) NUMBER
Ok

2024-06-19 20:27 UTC, MegaRedHand commented on src/codegen/context.rs
> +    #[allow(clippy::too_many_arguments)]
I don't think this is necessary in this case.

2024-06-19 20:42 UTC, MegaRedHand requested changes

2024-06-19 20:42 UTC, MegaRedHand commented on src/codegen/operations.rs
> +            AllocaOptions::new().elem_type(Some(TypeAttribute::new(h160.into()))),
Let's do the alloca for an uint256 instead.

2024-06-19 20:42 UTC, MegaRedHand commented on src/syscall.rs
> +        dbg!("{}", &self.db);
We can remove this now.

2024-06-19 20:42 UTC, MegaRedHand commented on src/syscall.rs
> +                dbg!("NONE");
Same here

2024-06-19 20:42 UTC, MegaRedHand commented on tests/evm.rs
> +fn balance_with_unexisting_account() {
```suggestion
fn balance_with_non_existent_account() {
```

2024-06-19 20:42 UTC, MegaRedHand commented on src/syscall.rs
> +    pub extern "C" fn get_balance(&mut self, address: &U256, balance: &mut U256) {
Let's rename it to `store_in_...` like the rest

2024-06-19 20:42 UTC, MegaRedHand commented on tests/evm.rs
> +fn balance_with_unexisting_account() {
Also, let's add another test for addresses that use the whole 256 bits (which are obviously invalid/non-existent).

2024-06-24 19:18 UTC, ricomateo commented
LGTM @MegaRedHand

2024-06-24 20:21 UTC, MegaRedHand approved these changes
LGTM

2024-06-25 13:18 UTC, merged