feat: implement PREVRANDAO opcode
lambdaclass/evm_mlir pull request #274
Opened 2024-06-18 15:50 UTC by ricomateo

Closes #50 
This PR implements code generation for [PREVRANDAO](https://www.evm.codes/#44?fork=cancun) opcode.

2024-06-18 18:00 UTC, JulianVentura commented
LGTM

2024-06-19 20:05 UTC, MegaRedHand requested changes

2024-06-19 20:05 UTC, MegaRedHand commented on src/syscall.rs
> +        }
We should set it to zero when randao isn't set:
```rust
let randao = self.env.block.prevrandao.unwrap_or_default();
prevrandao = ...;
```

2024-06-25 14:28 UTC, MegaRedHand reviewed
Please fix conflicts

2024-06-25 14:28 UTC, MegaRedHand commented on tests/evm.rs
> +type B256 = ethereum_types::U256;
This shouldn't be here

2024-06-25 14:28 UTC, MegaRedHand commented on tests/evm.rs
> +fn run_program_assert_bytes_result(
There're new functions in main to do this

2024-07-01 22:39 UTC, MegaRedHand commented on src/codegen/context.rs
> +    #[allow(unused)]
This isn't needed

2024-07-01 22:39 UTC, MegaRedHand commented on src/program.rs
>      // DIFFICULTY = 0x44,
We can remove `DIFFICULTY`. It was replaced in https://eips.ethereum.org/EIPS/eip-4399

2024-07-01 22:39 UTC, MegaRedHand commented on src/env.rs
> +    pub prevrandao: Option<U256>,
This should be a `Option<B256>`

2024-07-02 17:57 UTC, MegaRedHand approved these changes
LGTM

2024-07-02 17:57 UTC, merged