feat: implement BLOBHASH opcode
lambdaclass/evm_mlir pull request #275
Opened 2024-06-18 17:53 UTC by ricomateo

Closes #55 
This PR implements code generation for the [BLOBHASH](https://www.evm.codes/#49?fork=cancun) opcode.

2024-06-19 18:52 UTC, JulianVentura commented on src/syscall.rs
> +        if index < self.env.tx.blob_hashes.len() {
Here you can remove the len check and call `self.env.tx.blob_hashes.get(index)` instead. That will return you an Option which you can match over.

2024-06-19 19:48 UTC, JulianVentura approved these changes
LGTM

2024-06-19 20:42 UTC, ricomateo commented
@MegaRedHand this one is ready for review

2024-06-25 14:37 UTC, MegaRedHand requested changes

2024-06-25 14:37 UTC, MegaRedHand commented on src/syscall.rs
> +        let aux = self.env.tx.blob_hashes.get(index);
We can use `unwrap_or_default` here

2024-06-25 14:37 UTC, MegaRedHand commented on src/syscall.rs
> +        let index = index.lo as usize;
We should return zero when index is bigger than a `usize`

2024-07-02 18:23 UTC, MegaRedHand requested changes
Left some comments

2024-07-02 18:23 UTC, MegaRedHand commented on src/syscall.rs
> +        *blobhash = usize::try_from(index.lo).map_or(U256::default(), |idx| {
We should check `index.hi` is zero.

2024-07-02 18:23 UTC, MegaRedHand commented on src/syscall.rs
> +        });
This is a bit confusing. Generally, we have a chain of transformations (`map`, `and`, etc.), and at the end a single `unwrap`. In this case:

```suggestion
        *blobhash = usize::try_from(index.lo).and_then(|idx| {
            self.env
                .tx
                .blob_hashes
                .get(idx)
        })
        .map(U256::from_be_bytes)
        .unwrap_or_default();
```

2024-07-02 18:42 UTC, JulianVentura commented on src/syscall.rs
> +        });
Yep, that's way better. Thanks for the idea.

2024-07-02 18:42 UTC, JulianVentura commented on src/env.rs
> +type B256 = U256;
Done

2024-07-02 19:03 UTC, JulianVentura commented on src/syscall.rs
> +        *blobhash = usize::try_from(index.lo).map_or(U256::default(), |idx| {
Done

2024-07-02 21:18 UTC, MegaRedHand approved these changes
LGTM

2024-07-02 22:05 UTC, merged