feat: implement EXTCODESIZE opcode
lambdaclass/evm_mlir pull request #276
Opened 2024-06-18 19:56 UTC by ricomateo

Closes #41 
This PR implements code generation for the [EXTCODESIZE](https://www.evm.codes/#3b?fork=cancun) opcode.

2024-06-19 19:15 UTC, JulianVentura requested changes
It looks good to me. Just correct the readme to include the opcode in implemented list.

2024-06-19 19:15 UTC, JulianVentura commented on src/program.rs
> +            Operation::ExtcodeSize => vec![Opcode::EXTCODESIZE as u8],
nit: Try to maintain the order of the operations given in the `enum Opcode`

2024-06-19 19:22 UTC, ricomateo commented on README.md
> -1. (0x3B) EXTCODESIZE
nice catch!

2024-06-19 19:46 UTC, JulianVentura approved these changes
LGTM @MegaRedHand

2024-06-28 18:10 UTC, MegaRedHand requested changes

2024-06-28 18:10 UTC, MegaRedHand commented on src/constants.rs
> +    pub const EXTCODESIZE: i64 = 0;
I don't think we need to have this one

2024-06-28 18:10 UTC, MegaRedHand commented on src/program.rs
> +    EXTCODESIZE = 0x3B,
Can you reorder these?

2024-06-28 18:10 UTC, MegaRedHand commented on src/syscall.rs
> +        }
The `DatabaseError` is an external error, and should be handled as such. This mapping of "unknown" -> 0 should be handled inside `code_by_address`.

2024-06-28 18:10 UTC, MegaRedHand commented on src/syscall.rs
> +        let address = [&address_hi_bytes[12..16], &address_lo_bytes[..]].concat();
We should first check that the first 12 bytes are zero. If not, we should return a balance of 0.

2024-07-02 17:43 UTC, MegaRedHand approved these changes
Left some minor comments, but LGTM

2024-07-02 17:43 UTC, MegaRedHand commented on src/codegen/context.rs
> +    #[allow(unused)]
This isn't needed

2024-07-02 17:43 UTC, MegaRedHand commented on src/syscall.rs
> +        }
nit: you can instead do

```rust
Address::try_from(address).map(|x| self.db.code_by_address(x).len()).unwrap_or(0) as _
```

2024-07-02 17:53 UTC, JulianVentura commented on src/syscall.rs
> +        }
Cool

2024-07-02 18:11 UTC, merged