feat: implement EXTCODECOPY opcode
lambdaclass/evm_mlir pull request #290
Opened 2024-06-19 17:44 UTC by ricomateo

Closes #42 
This PR implements code generation for the [EXTCODECOPY](https://www.evm.codes/#3c?fork=cancun) opcode.

2024-06-24 18:38 UTC, TomasArrachea commented on src/codegen/operations.rs
> +    // TODO: add dynamic gas cost
We can remove this TODO since the cost is implemented. Instead, we can add one for the cold dynamic cost that is missing.

2024-06-24 18:38 UTC, TomasArrachea approved these changes
LGTM
@MegaRedHand

2024-06-26 14:40 UTC, MegaRedHand requested changes

2024-06-26 14:40 UTC, MegaRedHand commented on src/syscall.rs
> +            Err(_) => return,
We should copy zeros when the account doesn't exist.

2024-06-26 14:40 UTC, MegaRedHand commented on src/syscall.rs
> +        let address = [&address_hi_bytes[12..16], &address_lo_bytes[..]].concat();
We should first check if the first 12 bits are set. In that case, the address is invalid and we write zeros

2024-06-26 14:40 UTC, MegaRedHand commented on tests/evm.rs
> +fn extcodecopy_with_offset_out_of_bounds() {
Please add a test with an invalid address (first 12 bytes being non-zero)

2024-06-28 21:23 UTC, MegaRedHand commented on tests/evm.rs
> +    env.tx.gas_limit = 999_999;
This isn't needed since we fixed the default gas limit.

2024-06-28 21:23 UTC, MegaRedHand commented on tests/evm.rs
> +    env.tx.gas_limit = 999_999;
This too

2024-06-28 21:25 UTC, MegaRedHand commented on src/syscall.rs
> +impl TryFrom<U256> for Address {
Let's change this to a reference (`&U256`). That way we don't have to copy...

2024-06-28 21:25 UTC, MegaRedHand commented on src/syscall.rs
> +        let Ok(address) = Address::try_from(*address_value) else {
...here

2024-06-28 22:14 UTC, MegaRedHand approved these changes
LGTM

2024-06-28 22:14 UTC, merged