Implement opcode SELFBALANCE
lambdaclass/evm_mlir pull request #291
Opened 2024-06-19 18:06 UTC by JulianVentura

Closes #53 
This PR implements the opcode SELFBALANCE with tests.

2024-06-19 18:31 UTC, FrancoGiachetta commented
LGTM

2024-06-19 18:32 UTC, FrancoGiachetta approved these changes
LGTM

2024-06-25 18:33 UTC, MegaRedHand commented on src/db.rs
> +    pub fn with_accounts(self, new_accounts: HashMap<Address, DbAccount>) -> Self {
Can we change this to receive a single account? Then we can just chain it when multiple accounts are needed.

2024-06-25 18:33 UTC, MegaRedHand commented on src/db.rs
> +        let block_hashes = self.block_hashes;
No need to clone here. You can just declare `mut self`, modify that, and then return it.

2024-06-25 18:33 UTC, MegaRedHand commented on src/db.rs
> +        let mut accounts = self.accounts.clone();
Same here. Just declare `mut self`:

```rust
fn with_accounts(mut self, ...) -> Self {
    self.accounts.extend(...);
    self
}
```

2024-06-25 18:41 UTC, MegaRedHand requested changes

2024-06-25 18:41 UTC, MegaRedHand commented on src/syscall.rs
> +        };
You can use `unwrap_or_default` to simplify this.

2024-06-25 18:41 UTC, MegaRedHand commented on tests/evm.rs
> +}
Can we add an example that checks that `SelfBalance` does the same as [`Address`, `Balance`] ?

2024-06-25 19:23 UTC, JulianVentura commented on tests/evm.rs
> +}
Yes, that's a good one!

2024-06-25 20:22 UTC, MegaRedHand approved these changes
LGTM

2024-06-25 20:22 UTC, MegaRedHand commented on src/db.rs
> +        }
```suggestion
        self
```

2024-06-25 20:33 UTC, merged