Implement CALL opcode
lambdaclass/evm_mlir pull request #303
Opened 2024-06-26 14:44 UTC by JulianVentura

Closes #76 
This PR implements the CALL opcode with tests.

2024-07-02 18:35 UTC, MegaRedHand commented on src/syscall.rs
> +        EU256::from_big_endian(&bytes)
Can we use shifting and adding instead of dealing with strings?

2024-07-02 18:37 UTC, MegaRedHand commented on src/constants.rs
> +    pub const HALT_RETURN_CODE: u32 = 2;
These should be `u8`

2024-07-02 18:37 UTC, MegaRedHand commented on src/constants.rs
> +    pub const EMPTY_CALLE_COST: u64 = 25000;
typo
```suggestion
    pub const EMPTY_CALLEE_COST: u64 = 25000;
```

2024-07-02 18:46 UTC, MegaRedHand commented on src/codegen/context.rs
> +        let return_error_code = start_block
We don't necessarily need to halt here right? HALT is the same as REVERTED in spec terms, and when the inner context reverts a 0 is pushed to the stack while execution continues.

2024-07-02 18:47 UTC, MegaRedHand commented on tests/evm.rs
> +    // Calee
typo
```suggestion
    // Callee
```

2024-07-02 19:16 UTC, JulianVentura commented on tests/evm.rs
> +fn run_program_assert_gas_exact_aux(mut env: Env, db: Db, needed_gas: u64) {
I have used that not-so-nice name on purpose. I created the issue #310 to modify the name of it and refactor the already existing tests which are using the old function with similar name `run_program_assert_gas_exact`. Anyways, I can change the name and modify that issue if you want.

2024-07-02 19:33 UTC, JulianVentura commented on src/syscall.rs
> +        EU256::from_big_endian(&bytes)
Is `concat` method using strigns? If I'm not mistaken, [this is the documentation](https://doc.rust-lang.org/1.30.0/std/slice/trait.SliceConcatExt.html), and it doesn't seem to be using strings underneath. I can implement this using shift and additions as you mentioned, but it will still need two `U256` allocs. We would have to run some benchmarks in order to decide which is faster. Do you want me to make the change?

2024-07-02 19:49 UTC, JulianVentura commented on src/codegen/context.rs
> +        let return_error_code = start_block
Ok, I didn't know that HALT was the same as REVERT in spec terms. I'll check into that.

2024-07-02 19:55 UTC, MegaRedHand commented on tests/evm.rs
> +fn run_program_assert_gas_exact_aux(mut env: Env, db: Db, needed_gas: u64) {
Ok, but please change the name. I don't think we need to move all tests to use this function, but we may refactor the other one to call this one.

2024-07-02 19:59 UTC, MegaRedHand commented on src/syscall.rs
> +        EU256::from_big_endian(&bytes)
With strings, I'm referring to byte strings (i.e. slices or `&[u8]`) not `String`s. I'm asking for this change because dealing only with numbers makes code simpler to understand. Moving on to bytes makes us have to deal with things like endianness.

2024-07-03 13:38 UTC, JulianVentura commented on src/constants.rs
> +    pub const HALT_RETURN_CODE: u32 = 2;
Done

2024-07-03 13:39 UTC, JulianVentura commented on src/codegen/context.rs
> +        let return_error_code = start_block
Done

2024-07-03 13:41 UTC, JulianVentura commented on src/constants.rs
> +    pub const EMPTY_CALLE_COST: u64 = 25000;
Done

2024-07-03 13:41 UTC, JulianVentura commented on tests/evm.rs
> +    // Calee
Done

2024-07-03 13:45 UTC, JulianVentura commented on src/syscall.rs
> +        EU256::from_big_endian(&bytes)
Done

2024-07-03 14:23 UTC, JulianVentura commented on src/codegen/operations.rs
> +    expand_memory_from_offset_and_size(
Done

2024-07-03 14:25 UTC, JulianVentura commented on tests/evm.rs
> +fn run_program_assert_gas_exact_aux(mut env: Env, db: Db, needed_gas: u64) {
Done

2024-07-03 15:33 UTC, MegaRedHand requested changes

2024-07-03 15:33 UTC, MegaRedHand commented on src/codegen/context.rs
> +        // Extend the 32 bits result to 256 bits
```suggestion
        // Extend the 8 bits result to 256 bits
```

2024-07-03 15:33 UTC, MegaRedHand commented on src/db.rs
> +            && self.code.clone().unwrap_or_default().is_empty()
Instead of cloning here, we can check if the `code_hash` equals the empty hash: `0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`. Besides, `code` is just the cached value. `None` only means "this should be fetched from DB".

2024-07-03 15:33 UTC, MegaRedHand commented on src/syscall.rs
> +        let bytecode = self.db.code_by_address(callee_address);
This should use `db.basic` -(if code is None)-> `db.code_by_hash`. In fact, we could add it to the `Database` trait with a default implementation.

2024-07-03 15:33 UTC, MegaRedHand commented on tests/evm.rs
> +    let caller_call_cost = 100 + 9000 + 25000;
Can we use the constants here?

2024-07-03 15:33 UTC, MegaRedHand commented on src/syscall.rs
> +        };
This shouldn't be changed, as the `ORIGIN` remains the same. The `CALLER` should be taken from somewhere else. Maybe some struct representing the "call frame", which stores related metadata.

2024-07-03 18:51 UTC, JulianVentura commented on src/codegen/context.rs
> +        // Extend the 32 bits result to 256 bits
Done

2024-07-03 19:08 UTC, JulianVentura commented on src/db.rs
> +            && self.code.clone().unwrap_or_default().is_empty()
Done

2024-07-03 20:23 UTC, JulianVentura commented on tests/evm.rs
> +    let caller_call_cost = 100 + 9000 + 25000;
Done

2024-07-03 20:23 UTC, JulianVentura commented on src/syscall.rs
> +        };
Done

2024-07-04 13:18 UTC, MegaRedHand approved these changes
Good work!

2024-07-04 14:16 UTC, JulianVentura commented on src/syscall.rs
> +        let bytecode = self.db.code_by_address(callee_address);
Done

2024-07-04 14:52 UTC, MegaRedHand requested changes

2024-07-04 14:52 UTC, MegaRedHand commented on src/db.rs
> +    fn code_by_address(&mut self, address: Address) -> Result<Bytecode, Self::Error>;
Let's add a default implementation so it remains backwards-compatible

2024-07-04 14:52 UTC, MegaRedHand commented on src/syscall.rs
> +        //TODO: Here we are returning 0 if a Database error occurs. Check this
Let's add a `eprintln!` call on fail (and leave the TODO).

2024-07-04 14:52 UTC, MegaRedHand commented on src/syscall.rs
> +        let code = self.db.code_by_address(address).unwrap_or_default();
Same

2024-07-04 15:55 UTC, JulianVentura commented on src/db.rs
> +    fn code_by_address(&mut self, address: Address) -> Result<Bytecode, Self::Error>;
Done

2024-07-04 16:38 UTC, JulianVentura commented on src/syscall.rs
> +        //TODO: Here we are returning 0 if a Database error occurs. Check this
Done

2024-07-04 16:38 UTC, JulianVentura commented on src/syscall.rs
> +        let code = self.db.code_by_address(address).unwrap_or_default();
Done

2024-07-04 16:50 UTC, MegaRedHand approved these changes

2024-07-04 17:41 UTC, merged