add gas consumption to SSTORE operation
lambdaclass/evm_mlir pull request #304
Opened 2024-06-27 19:01 UTC by TomasArrachea

Closes #283 

This PR implements the dynamic gas costs of the SSTORE operation.

2024-07-01 20:38 UTC, MegaRedHand commented on src/syscall.rs
> +        }
Can you simplify this?

2024-07-01 20:38 UTC, MegaRedHand commented on src/syscall.rs
> +        }
This too.

2024-07-01 20:38 UTC, MegaRedHand commented on src/codegen/operations.rs
> +            .into(),
We can use `arith::cmpi` that has simpler parameters.

2024-07-01 20:38 UTC, MegaRedHand commented on src/codegen/operations.rs
> +    let return_block = region.append_block(Block::new(&[]));
Let's rename it to `end_block`.

2024-07-01 20:38 UTC, MegaRedHand commented on src/syscall.rs
> +    gas_refund: Option<i64>,
1. Why an `Option`?
2. Why signed?

2024-07-01 20:38 UTC, MegaRedHand commented on src/syscall.rs
> +        self.db.write_storage(self.env.tx.caller, key, value);
We should do this only after the transaction finishes.

2024-07-01 20:38 UTC, MegaRedHand commented on src/syscall.rs
> +        }
Can we return the gas cost instead and check this in the Rust side?

2024-07-02 17:55 UTC, MegaRedHand commented on src/codegen/operations.rs
> +        .into();
Let's do `gas_counter - gas_cost` first, so we avoid adding here.

2024-07-02 17:55 UTC, MegaRedHand commented on src/syscall.rs
> +            .unwrap_or(self.db.read_storage(address, key));
We use `*_or_else` functions when computation should be done lazily (like here).
```suggestion
            .unwrap_or_else(|| self.db.read_storage(address, key));
```

2024-07-02 21:17 UTC, MegaRedHand requested changes
Looks good! Left one coment, but should be good to go once fixed

2024-07-02 22:25 UTC, TomasArrachea commented on src/syscall.rs
> +            20_000
You are right, but i think that condition is missing the case where `original == current == value`. I made some changes

2024-07-03 14:24 UTC, MegaRedHand approved these changes
LGTM

2024-07-03 14:31 UTC, merged