feat: implement initial gas validation
lambdaclass/evm_mlir pull request #354
Opened 2024-07-15 19:04 UTC by TomasArrachea

Closes #350 

This PR implements the initial check of the transaction gas.

2024-07-16 13:21 UTC, JulianVentura requested changes
Some minor changes on tests, the rest looks good to me.

2024-07-16 13:21 UTC, JulianVentura commented on tests/evm.rs
> +    env.tx.gas_limit = 1000 + gas_cost::TX_BASE_COST;
Same

2024-07-16 13:21 UTC, JulianVentura commented on tests/evm.rs
> +    env.tx.gas_limit = 1000 + gas_cost::TX_BASE_COST;
Same

2024-07-16 14:17 UTC, JulianVentura approved these changes

2024-07-17 10:27 UTC, MegaRedHand approved these changes
LGTM

2024-07-17 13:56 UTC, merged