Journal update
lambdaclass/evm_mlir pull request #359
Opened 2024-07-17 19:05 UTC by JulianVentura

### Description

Update journal to be used as a cache of database.

Closes #334

2024-07-19 19:33 UTC, JulianVentura commented on bench/revm_comparison/src/lib.rs
> +    let mut context = SyscallContext::new(env, journal, Default::default());
Hmmm I don't think so, because on `SyscallContext::call` we use the `Journal::eject_base` to get a new `Journal` instance from the current context journal. Then we create a new instance of `SyscallContext` with it.
After the sub-context finishes execution, we use its journal to extend the current context `self.journal` with either `Journal::extend_from_success` or `Journal::extend_from_reverted`.

[Here you can see it](https://github.com/lambdaclass/evm_mlir/blob/11f74b483115ebd605aed0fe0ee79a4a126c5735/src/syscall.rs#L377)

2024-07-19 19:35 UTC, JulianVentura commented on src/db.rs
> +    pub fn _store_contract(&mut self, account: &AccountInfo) {
Sure!

2024-07-19 19:35 UTC, JulianVentura commented on src/db.rs
> +            //receives a transfer? That balance will be lost since it wont be commited
You are right!

2024-07-23 15:01 UTC, MegaRedHand approved these changes
LGTM

2024-07-23 15:01 UTC, MegaRedHand commented on src/lib.rs
> +    pub fn transact_and_commit(&mut self) -> Result<ExecutionResult, EVMError> {
Let's rename to [`transact_commit`](https://docs.rs/revm/12.1.0/revm/struct.Evm.html#method.transact_commit)
```suggestion
    pub fn transact_commit(&mut self) -> Result<ExecutionResult, EVMError> {
```

2024-07-23 15:01 UTC, MegaRedHand requested changes
.

2024-07-23 15:33 UTC, MegaRedHand approved these changes

2024-07-23 15:47 UTC, merged