First implementation of access lists
lambdaclass/evm_mlir pull request #373
Opened 2024-08-28 19:09 UTC by belfortep

This PR try to add `access lists` to the code, as it will be needed for different calculations of gas costs

2024-08-30 20:21 UTC, MegaRedHand commented on tests/evm.rs
> -fn precompile_staticcall_with_access_list_is_warm() {
Why were these tests removed?

2024-08-30 20:29 UTC, belfortep commented on tests/evm.rs
> -fn precompile_staticcall_with_access_list_is_warm() {
It tested the same behaviour as the `addresses_in_access_list_are_warm`, just changing the address to a precompile, thought it was unnecesary

2024-08-30 20:57 UTC, MegaRedHand commented on tests/evm.rs
> -fn precompile_staticcall_with_access_list_is_warm() {
Ok. But these weren't the tests that failed, right?

2024-08-30 21:59 UTC, belfortep commented on tests/evm.rs
> -fn precompile_staticcall_with_access_list_is_warm() {
Made an oopsie, the test I wanted to delete was the `coinbase` one, this test was the failing one that used the staticcall (now I understand why the CI started working)

2024-09-02 14:40 UTC, lazcanoluca commented on src/env.rs
> +
Can you create a couple of issues so we don't forget to add the remaining precompiles here?

2024-09-02 15:21 UTC, lazcanoluca approved these changes
lgtm

2024-09-02 19:41 UTC, belfortep commented on src/env.rs
> +
Just created the issue🫡

2024-09-09 14:27 UTC, JulianVentura requested changes

2024-09-09 14:27 UTC, JulianVentura commented on src/syscall.rs
> +        let is_cold = !(self.journal.key_is_warm(&address, &key)
Why are we asking both the journal and the access list for key warm/cold status? Can't we introduce all keys under `access_list` directly into journal cold/warm state from start?

2024-09-09 14:41 UTC, belfortep commented on src/syscall.rs
> +        let is_cold = !(self.journal.key_is_warm(&address, &key)
Oh, I had to ask that, maybe we can move the verification of warm keys from the `journal` directly to the `access_list`? If not, changing it to adding the keys to the `journal` from the start seems good

2024-09-09 14:58 UTC, JulianVentura commented on src/syscall.rs
> +        let is_cold = !(self.journal.key_is_warm(&address, &key)
Yeah both solutions would be ok. I actually like a bit more moving that responsability into Journal because I think it simplifies keys and addresses warm/cold state querying, and because it also simplifies how we may propagate those states back and forth from caller/callee on any external contract call. Journal was designed to wrap storage and key/address access state responsabilities with that in mind (and this of course has some drawbacks!).

We may change it in the future if we realize it's not a good idea.

2024-09-09 15:46 UTC, belfortep commented on src/syscall.rs
> +        let is_cold = !(self.journal.key_is_warm(&address, &key)
I'm facing a little problem with this, the Journal have the keys with the slots that have values associated to them, but in the AccessList, we only know the key we are using not what is in there, is it fine if we initialized that storage slot with default values?

2024-09-09 17:48 UTC, JulianVentura requested changes

2024-09-09 18:08 UTC, belfortep commented on bench/revm_comparison/src/lib.rs
> +    let journal = Journal::new(&mut db, &env.tx.access_list);
But creating the Journal and then adding the values couldn't lead to problems if we forgot them? If we are going to always add the accounts from the access lists to the journal it could make sense to add it to the ::new()

2024-09-09 21:55 UTC, JulianVentura reviewed
Here are some more comments.
As a general note, I think there are some bugs that we are not seeing because we are missing some tests or we are not testing properly.

Give them a look, please.

2024-09-09 21:55 UTC, JulianVentura commented on bench/revm_comparison/src/lib.rs
> +    let journal = Journal::new(&mut db, &env.tx.access_list);
It's actually a matter of preference. Both solutions are valid.
I like to separate access lists from the Journal constructor because you don't really need an access list to build a Journal, it's not a requirement. If for some reason we don't care passing an access list to the Journal, then we would have to pass an empty array or a `Default::default()` and that is a bit messy to me.
I think that a good solution would be to add a `with_prefetch(accounts: Vec<(Address, Vec<U256>)>)` method so you can have something like so:

```rust
let journal = Journal::new(&mut db).with_prefetch(&accounts);
```

This way you allow to instantiate the Journal without needing an access list and you keep the api clean so there is no code repetition.

2024-09-09 21:55 UTC, JulianVentura commented on src/env.rs
> +#[derive(Clone, Debug, Default)]
Do we really need to have this structure and functions?
We may need the gas calculation one, but I think it can be moved to some `utils` or something like that, so we keep the code base smaller and simpler.

2024-09-09 21:55 UTC, JulianVentura commented on src/syscall.rs
> +        // TODO: Probably here we need to add the access_list_cost to gas_used, but we need a refactor of most tests
We should create an issue for this.

2024-09-09 21:55 UTC, JulianVentura commented on src/syscall.rs
> +        let codesize = self.journal.code_by_address(&Address::from(address)).len();
Aren't we missing a check here for address warm/cold state?

2024-09-09 21:55 UTC, JulianVentura commented on src/syscall.rs
> +        let codesize = self.journal.code_by_address(&Address::from(address)).len();
We should call `account_is_warm` first, then `code_by_address`. 
I don't think we need an `add_account_as_warm` method if `code_by_address` already does a fetch (so it becomes warm). 

All of this should be tested.

2024-09-09 21:55 UTC, JulianVentura commented on src/syscall.rs
>                  let callee_account = match self.journal.get_account(&callee_address) {
What happens if the account exists, but it is cold? I think you are handling it as warm here.

2024-09-09 21:55 UTC, JulianVentura commented on src/syscall.rs
> +            let is_cold = !self.journal.account_is_warm(&address);
This will always return `warm`, because you are fetching that account before!

2024-09-10 12:13 UTC, belfortep commented on bench/revm_comparison/src/lib.rs
> +    let journal = Journal::new(&mut db, &env.tx.access_list);
I really like that way with the prefetch, you are right of passing an empty array or default could be bothersome, also the Journal don't really need an Access List, only needs the element inside it

2024-09-10 18:39 UTC, belfortep commented on src/syscall.rs
> +        let codesize = self.journal.code_by_address(&Address::from(address)).len();
Ah, so we should make that `code_by_address` be the one that makes the account warm/cold here?

2024-09-10 18:47 UTC, belfortep commented on src/syscall.rs
> +            let is_cold = !self.journal.account_is_warm(&address);
I'm getting a little dizzy, accounts in the journal are always `warm`, or we can have `cold` ones?

2024-09-10 19:06 UTC, JulianVentura commented on src/syscall.rs
> +        let codesize = self.journal.code_by_address(&Address::from(address)).len();
That's how we detect warm/cold state on an account if I'm not mistaken, by checking if it is cached in the journal internal `HashMap`.

2024-09-10 19:16 UTC, belfortep commented on src/syscall.rs
> +            let is_cold = !self.journal.account_is_warm(&address);
> What happens if the account exists, but it is cold? I think you are handling it as warm here.

Okay, but in this other comment aren't we doing the same but we need to verify the warm/cold access? or I'm missing something?

2024-09-11 12:41 UTC, belfortep commented on src/syscall.rs
> +        let codesize = self.journal.code_by_address(&Address::from(address)).len();
Just added some tests and seems the `add_account_as_warm` is needed if the address used is not in the journal from the start

2024-09-13 14:21 UTC, TomasArrachea approved these changes
LGTM

2024-09-17 16:13 UTC, JulianVentura approved these changes
LGTM!
Left you a small comment. You can merge after solving it.

2024-09-17 16:13 UTC, JulianVentura commented on src/codegen/operations.rs
> +fn get_gas_ptr<'c>(
This function doesn't actually return the gas ptr, does it? It allocates new memory where it stores a copy of the current gas counter. I would change the name to reflect that, because it may be misleading. 
And I would move this function to `src/utils.rs` with the other auxiliary functions.

2024-09-17 19:23 UTC, belfortep commented on src/codegen/operations.rs
> +fn get_gas_ptr<'c>(
You are right, changed it to `allocate_gas_counter_ptr` and moved it to `utils.rs`

2024-09-17 20:11 UTC, merged