CI parallelization
lambdaclass/evm_mlir pull request #417
Opened 2024-09-13 17:37 UTC by belfortep

Closes #416 
## Summary
This PR will change the ci for running the EF tests in 2 different workers

2024-09-13 20:02 UTC, MegaRedHand requested changes

2024-09-13 20:02 UTC, MegaRedHand commented on .github/workflows/ci.yml
> +        run: make test-eth-slow
We can use [`strategy.matrix`](https://docs.github.com/es/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow) to avoid duplicating this job. Something like:

```yaml
time-consuming-test:
  strategy:
    matrix:
      type: [fast, slow]
  steps:
    - ...
    - if: ${{ matrix.type == 'fast' }}
      run: make test-eth
    - if: ${{ matrix.type == 'slow' }}
      run: make test-eth-slow
```

2024-09-13 20:02 UTC, MegaRedHand commented on tests/time_consuming_test.rs
> +fn run_test(path: &Path, contents: String) -> datatest_stable::Result<()> {
Does this have any change from the one in `ef_tests.rs`? If not, we can move `ef_tests::run_test` to a module and call it from both files.

2024-09-16 12:56 UTC, belfortep commented on tests/time_consuming_test.rs
> +fn run_test(path: &Path, contents: String) -> datatest_stable::Result<()> {
Yes, this `run_test` have some little differences, the main one is that the `ef_tests.rs` one ignore groups of tests (including the time_consuming) and this not, but we can move most of the logic to a module as it's the same

2024-09-16 12:58 UTC, belfortep commented on .github/workflows/ci.yml
> +        run: make test-eth-slow
Didn't know about that, taking a look 👀

2024-09-16 14:01 UTC, MegaRedHand commented on tests/time_consuming_test.rs
> +fn run_test(path: &Path, contents: String) -> datatest_stable::Result<()> {
Let's extract the test running logic to a module, then.

2024-09-16 14:46 UTC, MegaRedHand approved these changes
LGTM

2024-09-16 19:11 UTC, juanimedone approved these changes

2024-09-16 20:30 UTC, merged