Create constants for precompiles' calldata lengths
lambdaclass/evm_mlir pull request #425
Opened 2024-09-16 20:42 UTC by iinaki

closes #390

2024-09-17 16:24 UTC, juanimedone commented
We have a `constants.rs` file so you could place the new constants there.

2024-09-17 17:16 UTC, iinaki commented
> We have a `constants.rs` file so you could place the new constants there.

Done!

2024-09-17 18:48 UTC, juanimedone requested changes

2024-09-17 18:48 UTC, juanimedone commented on src/precompiles.rs
> +            &calldata[start + G2_POINT_SIZE..start + (G2_POINT_SIZE * ECP_FIELD_SIZE)], // calldata[start + 128..start + 160]
This fixes `ecpairing` tests:
```suggestion
            &calldata[start + (G2_POINT_SIZE + ECP_FIELD_SIZE)
                ..start + (G2_POINT_SIZE + ECP_FIELD_SIZE * 2)], // calldata[start + 160..start + 192]
            &calldata[start + G2_POINT_SIZE..start + (G2_POINT_SIZE + ECP_FIELD_SIZE)], // calldata[start + 128..start + 160]
```

2024-09-17 18:48 UTC, juanimedone commented on src/precompiles.rs
> +        calldata[BF2_OFFSET_COUNT_INIT + BF2_VEC_ELEM_SIZE * 2..BF2_BLOCK_FLAG]
This should fix `blake2f` tests:
```suggestion
        calldata[BF2_OFFSET_COUNT_INIT + BF2_VEC_ELEM_SIZE..BF2_BLOCK_FLAG]
```

2024-09-17 18:51 UTC, juanimedone commented
That should make all tests run successfully. In order to fix the Lint CI you can merge `fix-gas-consumption` (I've already fixed it there) into this branch.

2024-09-17 19:17 UTC, iinaki commented on src/precompiles.rs
> +            &calldata[start + G2_POINT_SIZE..start + (G2_POINT_SIZE * ECP_FIELD_SIZE)], // calldata[start + 128..start + 160]
Done!

2024-09-17 19:17 UTC, iinaki commented on src/precompiles.rs
> +        calldata[BF2_OFFSET_COUNT_INIT + BF2_VEC_ELEM_SIZE * 2..BF2_BLOCK_FLAG]
Done!

2024-09-17 20:22 UTC, juanimedone approved these changes
LGTM

2024-09-17 21:02 UTC, juanimedone commented
Maybe you can change the title of the PR before merging as the new added constants are not only calldata lengths.

2024-09-17 21:05 UTC, igaray approved these changes

2024-09-18 14:08 UTC, MegaRedHand approved these changes

2024-09-18 14:18 UTC, merged