Fix eip3860-initcode from EF
lambdaclass/evm_mlir pull request #438
Opened 2024-09-19 15:12 UTC by belfortep

Closes #376 

## Summary
Tests that returns error when running the `evm.transact()` are now handled, fixed an error with conversion of types resulting on wrong gas consumption with Create transactions

2024-09-19 17:23 UTC, belfortep commented on tests/ef_tests_executor/test_utils.rs
> +                }
Oops, I always forget about `if let` and use `match`

2024-09-19 17:28 UTC, belfortep commented on tests/ef_tests_executor/test_utils.rs
> +            }
Where should we use `map_err` here?

2024-09-24 14:30 UTC, lazcanoluca requested changes

2024-09-24 14:30 UTC, lazcanoluca commented on src/constants.rs
> +    pub fn init_code_cost(init_code_length: u64) -> u64 {
I don't quite understand where does the 31 comes from. I looked a bit at the EIP but I don't get it.

2024-09-24 14:30 UTC, lazcanoluca commented on src/constants.rs
> +    pub fn init_code_cost(init_code_length: u64) -> u64 {
The EIP mentions:
> If length of transaction data (initcode) in a create transaction exceeds MAX_INITCODE_SIZE, transaction is invalid.

Should this check be done here, or is it assumed that `init_code_length` is already checked?

If the assumption is that `init_code_length` is < `MAX_INITCODE_SIZE`, an `assert` wouldn't hurt, just to enforce it.

Otherwise (if `init_code_length` can be > `MAX_INITCODE_SIZE`), I think the function should gracefully handle this case with `Result`.

2024-09-24 14:30 UTC, lazcanoluca commented on src/constants.rs
> +    pub fn init_code_cost(init_code_length: u64) -> u64 {
Finally, I think we should add a doc comment (with a link to the EIP), and a couple of unit tests.

2024-09-24 14:54 UTC, belfortep commented on src/constants.rs
> +    pub fn init_code_cost(init_code_length: u64) -> u64 {
to be honest, I don't really know where it comes from, I just accepted the mistery.
Probably is something that acts as a padding for initcode data that isn't a full 32-bytes word

2024-09-24 15:00 UTC, belfortep commented on src/constants.rs
> +    pub fn init_code_cost(init_code_length: u64) -> u64 {
Yes, the `init_code_length` is verified in the `validate_transaction` function, we could add the `assert` for an extra verification for a calm of mind

2024-09-24 15:07 UTC, belfortep commented on src/constants.rs
> +    pub fn init_code_cost(init_code_length: u64) -> u64 {
You are right, adding some test for the correct gas usage of Create transactions and some docs

2024-09-24 16:53 UTC, lazcanoluca commented on src/constants.rs
> +    pub fn init_code_cost(init_code_length: u64) -> u64 {
cool!

2024-09-24 16:53 UTC, lazcanoluca commented on src/constants.rs
> +    pub fn init_code_cost(init_code_length: u64) -> u64 {
awesome 🚀

2024-09-24 20:35 UTC, TomasArrachea commented on src/constants.rs
> +    pub fn init_code_cost(init_code_length: u64) -> u64 {
This operation computes the amount of 32-length chunks. The operation `int((x + 31) / 32) ` is analogous to `ceil(x / 32)`

2024-09-24 20:58 UTC, MegaRedHand commented on tests/ef_tests_executor/test_utils.rs
> +            }
I must've mistaken this to be a `match` on `Ok`/`Err` 🤔 
Let's leave it as-is.

2024-09-24 21:01 UTC, MegaRedHand approved these changes
LGTM

2024-09-24 21:23 UTC, lazcanoluca commented on src/constants.rs
> +    pub fn init_code_cost(init_code_length: u64) -> u64 {
I guess [.div_ceil()](https://doc.rust-lang.org/std/primitive.u64.html#method.div_ceil) could also be used.

2024-09-24 21:24 UTC, lazcanoluca approved these changes

2024-09-24 21:25 UTC, merged