feat: implement MUL opcode
lambdaclass/evm_mlir pull request #91
Opened 2024-05-29 17:11 UTC by Danikim01

Closes #5 
This PR implements the code generation for the MUL opcode

2024-05-29 19:49 UTC, MegaRedHand reviewed
Good work!! Please merge with main and address comments.

2024-05-29 19:49 UTC, MegaRedHand commented on tests/operations.rs
> +    let (a, b) = (2, 2);
Please make it two different numbers, so we can catch more errors.

2024-05-29 19:52 UTC, MegaRedHand requested changes
I forgot about this edge-case.

2024-05-29 19:52 UTC, MegaRedHand commented on tests/operations.rs
> +    ];
Please add a test for numeric overflow. When both numbers are big enough, the result should wrap around.

2024-05-29 20:14 UTC, Danikim01 commented on tests/operations.rs
> +    ];
what do you mean by wrap around?

2024-05-30 14:05 UTC, MegaRedHand commented on tests/operations.rs
> +    let program = vec![
This example doesn't check u256 overflow, just u8 overflow. For that, we should have a number close to 2^256 - 1, and multiply it by something that overflows it. Note that you'll need to manually represent the number with an array in the operation. Here's an example: https://github.com/lambdaclass/evm_mlir/blob/3ab4e499cca565c5b10f16efc7709e0ee4b98a9f/tests/operations.rs#L106-L119

2024-05-30 15:12 UTC, merged