implement sub opcode
lambdaclass/evm_mlir pull request #93
Opened 2024-05-29 17:47 UTC by FrancoGiachetta

Implementation of sub opecode

2024-05-29 19:08 UTC, juanbono commented on tests/operations.rs
> +    run_program_assert_result(program, b - a);
check if the subtraction wraps the result when you do : `0 - 10` or something like that. Please add a test like this one for this case.

2024-05-29 19:08 UTC, juanbono requested changes
see comments

2024-05-29 19:08 UTC, juanbono commented on tests/operations.rs
> +    run_program_assert_result(program, b - a);
same for U256::MAX + 10

2024-05-29 19:11 UTC, FrancoGiachetta commented on tests/operations.rs
> +    run_program_assert_result(program, b - a);
Checking

2024-05-29 20:00 UTC, FrancoGiachetta commented on tests/operations.rs
> +    run_program_assert_result(program, b - a);
How could I represent U256::MAX?

2024-05-29 20:09 UTC, FrancoGiachetta commented on tests/operations.rs
> +    run_program_assert_result(program, b - a);
<img width="1135" alt="Screenshot 2024-05-29 at 5 08 34 PM" src="https://github.com/lambdaclass/evm_mlir/assets/170033636/ee9468c2-a7ec-44df-92b0-c6f0db97df69">
It's giving me this

2024-05-30 13:13 UTC, MegaRedHand commented on tests/operations.rs
> +    run_program_assert_result(program, b - a);
You can build the array: `[0xFF; 32]`, and calculate the result manually.

2024-05-30 14:05 UTC, MegaRedHand commented on tests/operations.rs
> +
You're missing the `#[test]` tag

2024-05-30 14:10 UTC, FrancoGiachetta commented on tests/operations.rs
> +
My bad, fixing it

2024-05-30 14:13 UTC, FrancoGiachetta commented on tests/operations.rs
> +
Fixed

2024-05-31 19:02 UTC, juanbono approved these changes

2024-05-31 19:14 UTC, merged