feat: implement PUSH N opcodes
lambdaclass/evm_mlir pull request #94
Opened 2024-05-29 19:53 UTC by TomasArrachea

Closes #71 

This PR implements the code generation for all the [PUSH](https://www.evm.codes/#5f) opcodes.

2024-05-29 21:01 UTC, MegaRedHand commented on src/opcodes.rs
> +                }
Then here we can do `Operation::Push(BigUint::new(0));`

2024-05-29 21:01 UTC, MegaRedHand commented on src/codegen/operations.rs
> +        Operation::Push0 => codegen_push(context, region, [0; 32]),
And here we just have one arm with:

```rust
Operation::Push(value) => codegen_push(context, region, value)
```

2024-05-30 14:44 UTC, TomasArrachea commented on src/opcodes.rs
> +    Push4([u8; 4]),
Done!

2024-05-30 14:44 UTC, TomasArrachea commented on src/opcodes.rs
> +                }
Done!

2024-05-30 14:44 UTC, TomasArrachea commented on src/codegen/operations.rs
> +        Operation::Push0 => codegen_push(context, region, [0; 32]),
Done!

2024-05-30 14:50 UTC, MegaRedHand commented on tests/operations.rs
> +    Operation::Push(BigUint::from_bytes_be(bytes.into()))
We need to update the other tests

2024-05-30 14:56 UTC, MegaRedHand commented on tests/operations.rs
> +        new_push_op(&new_32_byte_immediate(b)),
Can we simplify this a bit? We can use `BigUint::from` for unsigned integers. Also, we can just move the `BigUint::from` into the declaration of `a` and `b`:

```rust
let a = BigUint::from(1);
let program = vec![Operation::Push(a)];
```

2024-05-30 15:10 UTC, TomasArrachea commented on tests/operations.rs
> +        new_push_op(&new_32_byte_immediate(b)),
I agree. Should we keep having tests for each pushn operation or just test for a single push in this way?

2024-05-30 15:14 UTC, MegaRedHand commented on tests/operations.rs
> +        new_push_op(&new_32_byte_immediate(b)),
We can write a single test that runs multiple programs, one for each push opcode.

2024-05-30 17:06 UTC, TomasArrachea commented on tests/operations.rs
> +        new_push_op(&new_32_byte_immediate(b)),
Ok. Although I think it will be better to keep the definition like this to avoid using a different crate to parse BigUInt to u8:
`
let a = 1_u8;
let program = vec![Operation::Push(BigUInt::from(a)];
`

2024-05-30 17:30 UTC, MegaRedHand commented on tests/operations.rs
> +    }
We should use some non-zero number:

```rust
    let value = BigUint::from(5);
    // Test for PUSH1, ... , PUSH32
    // TODO: do PUSH0 manually?
    for i in 0..32 {
        let shifted_value = value << (i * 8);
        let program = vec![Operation::Push(value)];
        run_program_assert_result(program, shifted_value.try_into().unwrap());
    }
```

2024-05-30 17:30 UTC, MegaRedHand commented on tests/operations.rs
> +        new_push_op(&new_32_byte_immediate(b)),
You can use [`TryFrom`](https://docs.rs/num-bigint/latest/num_bigint/struct.BigUint.html#impl-TryFrom%3CBigUint%3E-for-u8) for that.

Example:

```rust
let x = BigUint::from(5);
let b: u8 = TryFrom::<BigUint>::try_from(x).unwrap();
// This is the same as:
let c: u8 = x.try_into().unwrap();
```

2024-05-30 18:33 UTC, TomasArrachea commented on tests/operations.rs
> +    }
Ok, but using shift it's a problem because it makes the values too big to parse to u8 and check it, no?

2024-05-30 18:42 UTC, MegaRedHand commented on tests/operations.rs
> +    }
Yes. In that case, you can manually truncate it to that size:

```rust
let expected_result: u8 = (shifted_value % 256_u32).try_into().unwrap()
```

2024-05-30 19:00 UTC, MegaRedHand requested changes

2024-05-30 19:00 UTC, MegaRedHand commented on tests/operations.rs
> +    let shifted_value = BigUint::ZERO << (32 * 8);
Nit. No need for the shift

2024-05-30 19:00 UTC, MegaRedHand commented on src/opcodes.rs
> +                    i += 32;
Are you sure this is OK? I thought `PUSH0` increased the `pc` by 1 only (done outside the match).

2024-05-30 19:00 UTC, MegaRedHand commented on src/opcodes.rs
> +                    i += 31;
Same here.

2024-05-30 19:19 UTC, TomasArrachea commented on src/opcodes.rs
> +                    i += 32;
You are right!

2024-05-30 19:21 UTC, merged