feat: implement SAR opcode
lambdaclass/evm_mlir pull request #95
Opened 2024-05-29 20:06 UTC by ricomateo

Closes #28 
This PR implements the code generation for the [SAR](https://www.evm.codes/#1d?fork=cancun) opcode.

2024-05-31 19:15 UTC, MegaRedHand requested changes

2024-05-31 19:15 UTC, MegaRedHand commented on src/codegen/operations.rs
> +// }
We should remove this.

2024-05-31 19:15 UTC, MegaRedHand commented on src/codegen/operations.rs
> +    let revert_block = region.append_block(generate_revert_block(context)?);
We can remove this, in favor of `op_ctx.revert_block`

2024-05-31 19:15 UTC, MegaRedHand commented on src/codegen/operations.rs
> +        Operation::Sar => codegen_sar(op_ctx, region),
Please mark the opcode as implemented in the readme

2024-05-31 19:15 UTC, MegaRedHand commented on src/opcodes.rs
> +#[derive(Debug)]
We can remove this file

2024-05-31 19:15 UTC, MegaRedHand commented on tests/operations.rs
> +    //let expected_result: u8 = value.into() >> shift.into();
```suggestion
    let expected_result = (value >> shift).try_into().unwrap();
```

2024-05-31 19:15 UTC, MegaRedHand commented on tests/operations.rs
> +fn sar_with_negative_value_preserves_sign() {
We should include a test for the case where the shift is greater than 256.

2024-05-31 19:44 UTC, ricomateo commented on tests/operations.rs
> +fn sar_with_negative_value_preserves_sign() {
Done!

2024-05-31 19:49 UTC, juanbono requested changes
From the docs https://mlir.llvm.org/docs/Dialects/ArithOps/#arithshrsi-arithshrsiop:

```
The shrsi operation shifts an integer value of the first operand to the right by the value of the second operand. The first operand is interpreted as signed, and the second operand is interpreter as unsigned. The high order bits in the output are filled with copies of the most-significant bit of the shifted value (which means that the sign of the value is preserved). If the value of the second operand is greater or equal than bitwidth of the first operand, then the operation returns poison.
```

You should add a check for that last reason to avoid poisoned values.

2024-05-31 20:05 UTC, ricomateo commented
> From the docs https://mlir.llvm.org/docs/Dialects/ArithOps/#arithshrsi-arithshrsiop:
> 
> ```
> The shrsi operation shifts an integer value of the first operand to the right by the value of the second operand. The first operand is interpreted as signed, and the second operand is interpreter as unsigned. The high order bits in the output are filled with copies of the most-significant bit of the shifted value (which means that the sign of the value is preserved). If the value of the second operand is greater or equal than bitwidth of the first operand, then the operation returns poison.
> ```
> 
> You should add a check for that last reason to avoid poisoned values.

In those cases the operation should be reverted?

2024-05-31 21:13 UTC, Oppen commented
> @juanbono in those cases the operation should be reverted?

No. According to the EVM docs, there is no such requirement, so you'll have to either check before and keep the minimum between the actual value and the width or check for poison later and replace with `0x00..00` or `0xff..ff` depending on the sign bit.

2024-06-01 20:56 UTC, Oppen commented
You can use [minui](https://mlir.llvm.org/docs/Dialects/ArithOps/#arithminui-arithminuiop) on the `shift` value and a constant `255` to achieve that, unconditionally, before applying the shift. You would use the result instead of `shift` for that. That way you can satisfy the mlir requirements while implementing the EVM semantics. This should be doable without adding extra blocks.

2024-06-03 11:56 UTC, azteca1998 approved these changes

2024-06-03 11:56 UTC, azteca1998 commented on README.md
> +1. (0x1D) SAR
I've seen in other PRs they're asking to keep this list sorted by the opcode ID.

2024-06-03 12:50 UTC, ricomateo commented
> You can use [minui](https://mlir.llvm.org/docs/Dialects/ArithOps/#arithminui-arithminuiop) on the `shift` value and a constant `255` to achieve that, unconditionally, before applying the shift. You would use the result instead of `shift` for that. That way you can satisfy the mlir requirements while implementing the EVM semantics. This should be doable without adding extra blocks.

Done!

2024-06-03 12:57 UTC, ricomateo commented on README.md
> +1. (0x1D) SAR
Nice catch!

2024-06-03 13:20 UTC, Oppen commented on tests/operations.rs
> +fn sar_with_negative_value_preserves_sign() {
Let's also add one for a positive number (shift resulting in 0).

2024-06-03 14:05 UTC, ricomateo commented on tests/operations.rs
> +fn sar_with_negative_value_preserves_sign() {
Done!

2024-06-03 17:19 UTC, Oppen approved these changes

2024-06-03 18:40 UTC, MegaRedHand approved these changes
LGTM

2024-06-03 18:40 UTC, Oppen commented on src/program.rs
> +            x if x == Opcode::SWAP16 as u8 => Opcode::SWAP16,
Wow nice spot!

2024-06-03 18:44 UTC, juanbono approved these changes

2024-06-03 18:44 UTC, merged